---
abstract: 'Easier test cases for your L<DBIx::Class> applications'
author:
  - 'John Napiorkowski C<< <jjnapiork@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::DBIx::Class
name: Test-DBIx-Class
no_index:
  directory:
    - inc
    - t
requires:
  Config::Any: 0.19
  DBIx::Class: 0.08123
  DBIx::Class::Schema::PopulateMore: 0.15
  DBIx::Class::TimeStamp: 0.13
  DBIx::Class::UUIDColumns: 0.02005
  Data::UUID: 1.215
  Data::Visitor: 0.27
  Digest::MD5: 2.39
  Hash::Merge: 0.11
  List::MoreUtils: 0.22
  Moose: 1.10
  MooseX::Attribute::ENV: 0.01
  MooseX::Types: 0.23
  Path::Class: 0.21
  SQL::Translator: 0.11006
  Scalar::Util: 1.23
  Sub::Exporter: 0.982
  Test::Builder: 0.96
  Test::Deep: 0.106
  Test::mysqld: 0.11
  perl: 5.8.0
resources:
  homepage: http://search.cpan.org/dist/Test-DBIx-Class/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jjn1056/Test-DBIx-Class.git
version: 0.19
